### PR TITLE
fix(network): use wrapping ops to fix panic

### LINKED ISSUE #162: Fuzzer-identified panics
Hi, using a fuzzer with better features identified a number of crashes:

[crashes.zip](https://github.com/user-attachments/files/16185879/crashes.zip)

```
thread 'main' panicked at /home/mattop/boxcars/src/network/mod.rs:202:25:
attempt to subtract with overflow
```
\- OR -
```
thread 'main' panicked at /home/mattop/boxcars/src/network/mod.rs:185:23:
attempt to add with overflow
```

In order to be resistant to these crashes, it might be a good idea to use checked math like referenced here: https://github.com/nickbabcock/boxcars/issues/11#issuecomment-358477316

### PR DESCRIPTION
**Pull request by sigaloid**
Fixes #162

### CODE REVIEW

File: src/network/mod.rs [hunk 1]
```diff
@@ -199,7 +205,7 @@ pub(crate) fn parse(header: &Header, body: &ReplayBody) -> Result<NetworkFrames,
 
     // 1023 stolen from rattletrap
     let max_channels = header.max_channels().unwrap_or(1023) as u32;
-    let channel_width = crate::bits::bit_width(u64::from(max_channels)) - 1;
+    let channel_width = crate::bits::bit_width(u64::from(max_channels)).wrapping_sub(1);
```
Comment (nickbabcock) [inline src/network/mod.rs:208]: saturating sub seems like a better fit 🤔

Comment (sigaloid) [reply src/network/mod.rs]: Fixed :saluting_face:

**Review by nickbabcock — APPROVED** [review]
